micronaut.application.name=basic
micronaut.server.context-path=/api

# Management Endpoints
endpoints.all.enabled=true
endpoints.all.sensitive=false

# Static Resources
micronaut.router.static-resources.default.enabled=true
micronaut.router.static-resources.default.mapping=/**
micronaut.router.static-resources.default.paths=classpath:public

# I18n
micronaut.message-source.enabled=true
micronaut.message-source.basename=i18n/messages

# Include Metadata and Exception Stacktrace in API Response
application.api.response.include-metadata=true
application.api.response.include-exception-stacktrace=false